# REST

## login
POST http://localhost:9092/admin/auth/login
Content-Type: application/json

{
    "email": "<EMAIL>",
    "password": "<CHANGE-ME>",
    "rememberMe": false
}

## Register
## Forget Password
## Profile