services:
  db:
    image: postgres:16-alpine
    container_name: 69-s2-db
    ports:
      - "54321:5432"
    environment:
      - POSTGRES_PASSWORD=<CHANGE-ME>
      - POSTGRES_USER=<USER>
      - POSTGRES_DB=<USER>

  admin:
    image: dpage/pgadmin4:8.8
    container_name: 69-s2-admin
    ports:
      - "8082:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=<EMAIL>
      - PGADMIN_DEFAULT_PASSWORD=<CHANGE-ME>
      
  app:
    image: prawee/strapi
    container_name: 69-s2-app
    restart: always
    depends_on:
      - db
    ports:
      - "9092:1337"
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: <USER>
      DATABASE_USERNAME: <USER>
      DATABASE_PASSWORD: <CHANGE-ME>